version = 0.1
[default.deploy.parameters]
stack_name = "HttpAPIStack"
resolve_s3 = true
s3_prefix = "HttpAPIStack"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
